version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - POSTGRES_USER=postgres
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
volumes:
  db:
    driver: local